# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 골치의 블로그
email: p2r64h32@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  개발자 골치의 블로그입니다. 주로 웹기술 관련 내용을 다룹니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://golch.gitub.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  golch

# Build settings
markdown: kramdown

#disqus settings
disqus:
  id: "golch51"

# For better code blocks
highlighter: rouge
#pygments: true

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

sources:
  - _assets/css
  - _assets/images
  - _assets/javascripts
  - _assets/stylesheets
  - _assets/fonts
  - _assets/img
  - _assets/js
